version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4
  sfdx: circleci/salesforce-sfdx@1.0.0
  slack: circleci/slack@3.4.2
  node: circleci/node@3.0.0

_refs:
  install: &install
    name: Install dependencies
    command: |
      npm --version
      node --version
      npm install

variables:
  - &node-build-image
    - image: circleci/node:12.16.1-stretch

jobs:
  soql-builder-ui:
    docker: *node-build-image
    environment:
      PACKAGE_PATH: 'packages/soql-builder-ui'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run SOQL builder UI Unit Tests
          command: |
            echo 'Run SOQL builder UI Unit Tests'
            cd $PACKAGE_PATH
            yarn test
      #- slack/status:
      #    fail_only: true

  language-server:
    docker: *node-build-image
    environment:
      PACKAGE_PATH: 'packages/language-server'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: 'Language Server: Run LWC Unit Tests'
          command: |
            echo 'Language Server: Run LWC Unit Tests'
            cd $PACKAGE_PATH
            yarn test
      #- slack/status:
      #    fail_only: true

  sobject-metadata:
    docker: *node-build-image
    environment:
      PACKAGE_PATH: 'packages/sobject-metadata'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: 'Run Sobject Metadata Server Unit Tests'
          command: |
            echo 'Run Sobject Metadata Server Unit Tests'
            cd $PACKAGE_PATH
            yarn test
      #- slack/status:
      #    fail_only: true

  soql-model:
    docker: *node-build-image
    environment:
      PACKAGE_PATH: 'packages/soql-model'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: 'Run SOQL Model Server Unit Tests'
          command: |
            echo 'Run SOQL Model Server Unit Tests'
            cd $PACKAGE_PATH
            yarn test
      #- slack/status:
      #    fail_only: true

  notify_slack:
    docker: *node-build-image
    steps:
      - slack/notify:
          channel: web-tools-bot
          title: "Success: ${CIRCLE_USERNAME}'s commit-workflow"
          title_link: 'https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}'
          color: '#9bcd9b'
          message: "${CIRCLE_USERNAME}'s workflow <https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}|commit-workflow> in ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\n(${CIRCLE_BRANCH})"
          include_project_field: false
          include_visit_job_action: false
          include_job_number_field: false

workflows:
  version: 2
  commit-workflow:
    jobs:
      - soql-builder-ui
      - language-server
      - sobject-metadata
      - soql-model
      - notify_slack:
          requires:
            - soql-builder-ui
            - language-server
            - sobject-metadata
            - soql-model
